#!/usr/bin/env node
/**
 * Postinstall fixup for folder-scoped git deps.
 *
 * `github:org/repo#branch&path:/sub/folder` deps where the sub-folder has
 * no `package.json` are shipped by pnpm with a placeholder manifest:
 *
 *   {"_pnpmPlaceholder":"This file was generated by pnpm. ..."}
 *
 * The placeholder lacks `"type"`, so Node treats the package as CJS and
 * routes the bundled `.ts` files through its built-in type-stripper, which
 * refuses to run on anything inside `node_modules`. Forcing ESM lets the
 * `amaro/strip` loader transform them at runtime.
 *
 * The pnpm `readPackage` hook only mutates the in-memory manifest used for
 * resolution and never writes back to disk, so we patch the placeholders
 * here instead. Idempotent and safe to re-run.
 *
 * The script walks the on-disk pnpm store layout (`node_modules` plus
 * `node_modules/.pnpm/<name>@<spec>/node_modules/<name>`) and patches every
 * placeholder it finds, so newly added folder-scoped deps are covered
 * automatically without updating an allowlist.
 */
import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface PlaceholderManifest {
  _pnpmPlaceholder?: string;
  type?: string;
  [key: string]: unknown;
}

const here = dirname(fileURLToPath(import.meta.url));
const nodeModules = resolve(here, "..", "node_modules");

async function listDir(path: string) {
  try {
    return await readdir(path, { withFileTypes: true });
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw err;
  }
}

/**
 * Yields every `<pkgRoot>` directory we want to inspect:
 * - direct deps under `node_modules/<name>` and `node_modules/@scope/<name>`
 * - hoisted/virtual copies under `node_modules/.pnpm/<id>/node_modules/<name>`
 *   (and the same with scopes)
 */
async function* iterPackageRoots(root: string): AsyncGenerator<string> {
  for (const entry of await listDir(root)) {
    if (!entry.isDirectory()) continue;
    if (entry.name === ".bin") continue;

    if (entry.name === ".pnpm") {
      const pnpmRoot = resolve(root, ".pnpm");
      for (const pkgId of await listDir(pnpmRoot)) {
        if (!pkgId.isDirectory()) continue;
        yield* iterPackageRoots(resolve(pnpmRoot, pkgId.name, "node_modules"));
      }
      continue;
    }

    if (entry.name.startsWith("@")) {
      const scopeDir = resolve(root, entry.name);
      for (const scoped of await listDir(scopeDir)) {
        if (!scoped.isDirectory()) continue;
        yield resolve(scopeDir, scoped.name);
      }
      continue;
    }

    yield resolve(root, entry.name);
  }
}

async function patchPlaceholder(pkgRoot: string): Promise<boolean> {
  const manifestPath = resolve(pkgRoot, "package.json");
  let raw: string;
  try {
    raw = await readFile(manifestPath, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw err;
  }

  let manifest: PlaceholderManifest;
  try {
    manifest = JSON.parse(raw) as PlaceholderManifest;
  } catch {
    return false;
  }

  if (manifest._pnpmPlaceholder === undefined) return false;
  if (manifest.type === "module") return false;

  manifest.type = "module";
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  return true;
}

let patched = 0;
for await (const pkgRoot of iterPackageRoots(nodeModules)) {
  if (await patchPlaceholder(pkgRoot)) patched += 1;
}

if (patched > 0) {
  console.log(`[fix-placeholder-manifests] patched ${patched} placeholder package.json file(s)`);
}
